const shoppingCart = {
  menuData: {
    "data": {
      "shopping_cart": {
        "activity_info_list": [],
        "shopping_cart_icon": "",
        "shipping_fee_cart_tip": "另需配送费¥1",
        "full_minus_grad": "0.9",
        "bg_color": "",
        "balance_button": {
          "button_font_color": "",
          "button_pic_url": ""
        },
        "activity_info": {
          "is_only_online": true,
          "content": "",
          "policy": "[{\"priceHigher\":50.0,\"reduce\":23.0,\"priceLower\":35.0},{\"priceHigher\":70.0,\"reduce\":33.0,\"priceLower\":50.0},{\"priceHigher\":1.7976931348623157E308,\"reduce\":43.0,\"priceLower\":70.0}]",
          "type": 1
        },
        "self_delivery_tip": "支持自取",
        "min_fee_cart_tip": 12.6,
        "empty_shopping_cart_icon": "",
        "prompt_text": "满35减23;满50减33;满70减43"
      },
      "latest_bought": {
        "tag_icon": "http://p1.meituan.net/aichequan/6544f95cd7826c383d54fa5c881919e61386.png",
        "tag": "op0010",
        "orderlist_his": [],
        "tag_name": "买过",
        "tag_sequence": 0
      },
      "friend_status": 1,
      "poi_info": {
        "can_use_coupon": 1,
        "app_delivery_tip": "由美团快送提供配送服务",
        "cityId": 0,
        "epp_per_order_donation_amount": 0,
        "score": 0.0,
        "dp_score": 0.0,
        "restrict_toast": "",
        "poi_impress": {
          "title": "印象墙",
          "impress_label": [{
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"味道赞\"",
            "label_url": ""
          }, {
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"价格实惠\"",
            "label_url": ""
          }, {
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"包装好\"",
            "label_url": ""
          }, {
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"分量足\"",
            "label_url": ""
          }]
        },
        "epp_join_status": 0,
        "story_info": {
          "poi_logo_icon": "http://p1.meituan.net/aichequan/9785c871522e3f80114e5ffa840e89671540.png",
          "entrance_url": "http://i.waimai.meituan.com/node/brand/brandstory?poiid=5196d4566c301788a5",
          "poi_tab_icon": "http://p1.meituan.net/aichequan/c630ac6e0aa178a7a11153908c2ff1b23114.png"
        },
        "label_info": [{
          "content": "35减23",
          "activity_id": 0,
          "priority": 0,
          "label_background_color": "",
          "content_color": "#FB4E44",
          "priority_sort_index": 0,
          "icon_url": "",
          "type": 2,
          "poi_service_type": 0,
          "label_frame_color": "#FDC9C6"
        }, {
          "content": "50减33",
          "activity_id": 0,
          "priority": 0,
          "label_background_color": "",
          "content_color": "#FB4E44",
          "priority_sort_index": 0,
          "icon_url": "",
          "type": 2,
          "poi_service_type": 0,
          "label_frame_color": "#FDC9C6"
        }, {
          "content": "70减43",
          "activity_id": 0,
          "priority": 0,
          "label_background_color": "",
          "content_color": "#FB4E44",
          "priority_sort_index": 0,
          "icon_url": "",
          "type": 2,
          "poi_service_type": 0,
          "label_frame_color": "#FDC9C6"
        }, {
          "content": "5.93折起",
          "activity_id": 0,
          "priority": 0,
          "label_background_color": "",
          "content_color": "#FB4E44",
          "priority_sort_index": 0,
          "icon_url": "",
          "type": 2,
          "poi_service_type": 0,
          "label_frame_color": "#FDC9C6"
        }, {
          "content": "新客减1",
          "activity_id": 0,
          "priority": 0,
          "label_background_color": "",
          "content_color": "#FB4E44",
          "priority_sort_index": 0,
          "icon_url": "",
          "type": 2,
          "poi_service_type": 0,
          "label_frame_color": "#FDC9C6"
        }],
        "speed_refund_status": 0,
        "shippingReduceFee": 0.0,
        "longitude": 0,
        "discounts2": [{
          "id": 2,
          "display_code": 2,
          "sequence": 1,
          "icon_url": "http://p0.meituan.net/xianfu/f8bc8dffdbc805878aa3801a33f563cd1001.png",
          "type": 6,
          "use_icon_from_server": 1,
          "info": "门诊医疗服务整单9折（药品、血液、耗材、齿科、眼科无折扣）"
        }, {
          "id": 17,
          "display_code": 2,
          "sequence": 4,
          "icon_url": "http://p1.meituan.net/xianfu/9c997ecce6150671b8459738a26f8bd9767.png",
          "type": 19,
          "use_icon_from_server": 1,
          "info": "折扣商品5.93折起"
        }, {
          "id": 22,
          "display_code": 2,
          "sequence": 99,
          "icon_url": "http://p1.meituan.net/xianfu/1cc4324d7d2f59f2cccb6920b57cd0902048.png",
          "type": 0,
          "use_icon_from_server": 1,
          "info": "本店新用户立减1元, 新用户立减17元"
        }],
        "poi_back_pic_url": "http://p0.meituan.net/aichequan/0db65652de81b2140a9eb6c2183f3296361823.png",
        "min_price_tip": "起送 ¥18",
        "poi_coupon": {
          "coupon_list": []
        },
        "remind_infos": [],
        "new_user_discount_restrict_toast": "",
        "origin_shipping_fee_tip": "¥3",
        "buz_code": 0,
        "status": 1,
        "buz_type": 0,
        "shipping_fee": 3.0,
        "has_poi_env": false,
        "poi_service_label": {
          "title": "",
          "scheme_url": "",
          "service_label": []
        },
        "invoice_support": 0,
        "support_pay": 1,
        "across_book_offset_days": 0,
        "avg_delivery_time": 33,
        "bulletin": "上海艾儿贝佳妇产科医院参照DNV国际医院标准建设，医院开展妇科、产科、计划生育科、生殖健康与不孕症科、中医妇科、中西医结合科、泌尿外科、妇科疾病筛查、孕前优生健康检查等医疗服务，与各大国际保险公司建立了直接付费关系。艾儿贝佳医疗团队的组建坚持高标准，注重人才梯队建设，主管以上医疗人才大多来自于上海各大三甲医院的中青年骨干，形成了一支结构合理的医疗人才梯队。同时，艾儿贝佳妇产科医院聘请上海众多三甲医院妇产科、新生儿科专家来医院看诊、会诊或手术",
        "latitude": 0,
        "delivery_type": 0,
        "delivery_time_tip": "33分钟",
        "buz_menu_tip": "菜单",
        "poi_insurances": [],
        "poi_sell_status": 1,
        "promotion_head_pic_url": "",
        "pic_url": "/static/zhensuo1.jpg",
        "id": 470871157426160,
        "extraStatInfo": "",
        "dp_comment_number": 0,
        "distance": "2.1km",
        "min_price": 18.0,
        "name": "正新汉堡·炸鸡（东兰餐厅店）",
        "poi_prepare_time": "",
        "comment_number": 0,
        "is_meituan_delivery": true,
        "across_book_max_days": 0,
        "shipping_fee_tip": "配送 ¥1",
        "discount_restrict": 0,
        "poi_label": {
          "labels": [{
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"味道赞\"",
            "label_url": ""
          }, {
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"价格实惠\"",
            "label_url": ""
          }, {
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"包装好\"",
            "label_url": ""
          }, {
            "label_type": 3,
            "label_desc_text": "",
            "label_color": "",
            "scheme_sec_url": "",
            "label_priority": 0,
            "scheme_url": "",
            "label_text": "\"分量足\"",
            "label_url": ""
          }],
          "label_rank_field": ""
        },
        "is_favorite": 0,
        "is_sunshine": 0,
        "wm_poi_score": 4.5,
        "useRangeFeeEnum": "NO",
        "new_user_discount_restrict": 0,
        "shipping_time": "09:50-23:59",
        "address": "",
        "head_pic_url": "http://p0.meituan.net/business/655e8c7b2e65d035382bcba8d953723a243293.jpg",
        "share_tip": {
          "share_button_icon": "",
          "activity_id": 0,
          "share_info": {
            "content": "生活不只有诗和远方，还有美团外卖正新汉堡·炸鸡（东兰餐厅店）",
            "icon": "http://p0.meituan.net/waimaipoi/6126e47d09268a4b0bc418488d693a9038058.jpg",
            "title": "正新汉堡·炸鸡（东兰餐厅店）",
            "weixin_url": "pages/external/poi?poi_id=470871157426160&user_id=228577344&utm_source=7004",
            "url": "http://i.waimai.meituan.com/external/poi/470871157426160?utm_source=5913&amp;wmi_from=cpoiinfo&amp;user_id=228577344"
          },
          "description": "商家配送范围有限，建议分享给您附近的朋友",
          "description_icon": "",
          "channels": [2, 3]
        }
      },
      "recommend_food_info": {
        "log_field": {
          "recommend_food_type": 1
        },
        "title": "",
        "spu_list": []
      },
      "shopping_cart_entrance": {
        "content": "邀请拼单",
        "visible": 1,
        "icon_url": "http://p0.meituan.net/waimaipoi/6126e47d09268a4b0bc418488d693a9038058.jpg@420w_336h_1e_1c|watermark=1&&object=L2RwdGFrZWF3YXkvNWQxNTYwZjY1MDcwMzI0YzViZDUxNzlhMjIyYTk2Y2YyODMzOC5wbmc=&p=1|watermark=2&&text=5q2j5paw5rGJ5aChwrfngrjpuKHvvIjkuJzlhbDppJAuLi4=&type=UEZN&size=32&color=I0ZGRkZGRg==&p=1&x=20&y=270|watermark=2&&text=5ruhMzXlh48yMzvmu6E1MOWHjzMzO+a7oTcw5YePNDM=&type=UEZN&size=24&color=IzMzMzMzMw==&p=1&x=20&y=320.webp",
        "shop_cart_id": ""
      },
      "show_rcmd_pois": false,
      "patch_order_button_title": "",
      "container_template": {
        "code": 0,
        "is_page": false
      },
      "is_show_rcmd_pois": false,
      "food_spu_tags": [{
        "tags": [],
        "activity_tag": "",
        "icon": "",
        "tag": "100",
        "has_next_page": false,
        "type": 3,
        "tag_description": "",
        "tag_category_pic": "",
        "big_pic_url": "",
        "current_page": 0,
        "selected": 0,
        "product_count": 0,
        "description": "",
        "sequence": 0,
        "name": " 发育科",
        "activity_info": {
          "icon_url": "",
          "scheme_url": "",
          "activity_text": ""
        },
        "spus": [{
          "log_field": {
            "recommend_label_type": 0,
            "product_label_type_list": [3]
          },
          "video_icon": "http://p0.meituan.net/aichequan/c38e0125140af99491af1410229ff2db1721.png",
          "status_description": "",
          "tag": "61345968",
          "recommend_description": "",
          "month_saled_content": "门诊时间：周二全天、周四全天",
          "promotion": {
            "height": 0,
            "width": 0,
            "sku_info_color": "",
            "label_pic": "",
            "promotion_text": ""
          },
          "product_label_picture_list": [{
            "height": 30,
            "picture_url": "http://p0.meituan.net/aichequan/e4384905366c1a4d3a3d8c7831c79f7c1346.png",
            "width": 60
          }],
          "food_label_text": "",
          "id": 747123773,
          "min_price": 14.9,
          "description": "院长/主任医师",
          "attrs": [],
          "activity_policy": {
            "discount_by_count": {
              "count": 0,
              "discount": 1.0
            }
          },
          "name": "金星明",
          "praise_num": 17,
          "activity_type": 0,
          "praise_content": "赞17",
          "praise_num_new": 17,
          "activity_tag": "",
          "status": 0,
          "mport_sell_status": 0,
          "month_saled": 754,
          "label_text": "",
          "sku_label": "规格",
          "realStatus": 0,
          "promotion_info": "",
          "virtualStatus": 0,
          "picture": "/static/doctor1.png",
          "unit": "份",
          "tread_num": 5,
          "shippingTimeX": "",
          "sequence": 0,
          "status_remind_list": [],
          "product_label_picture": "",
          "skus": [{
            "spec": "",
            "real_stock": -1,
            "origin_price": 14.9,
            "status": 0,
            "promotion": {
              "height": 0,
              "width": 0,
              "sku_info_color": "",
              "label_pic": "",
              "promotion_text": ""
            },
            "promotion_info": "",
            "box_num": 1.0,
            "restrict": 0,
            "id": 809829128,
            "picture": "http://p1.meituan.net/wmproduct/372473766b64be5f21e376e3dd9ff9052854075.png",
            "stock": 0,
            "price": 14.9,
            "description": "分量超足，食材丰富，一口下去就可以咬到肉，不容错过的美味",
            "activity_stock": 0,
            "min_order_count": 1,
            "box_price": 1.0
          }],
          "share_tip": {
            "share_button_icon": "",
            "activity_id": 0,
            "share_info": {
              "content": "",
              "icon": "",
              "title": "",
              "weixin_url": "",
              "url": ""
            },
            "description": "",
            "description_icon": "",
            "channels": []
          },
          "friends_nickname_praise_content": "",
          "food_label_pic": "",
          "activity_tag_id": "",
          "friends_praise_content": ""
        }],
        "buzType": 0
      }, {
        "tags": [],
        "activity_tag": "discount",
        "icon": "",
        "tag": "act17",
        "has_next_page": false,
        "type": 2,
        "tag_description": "折扣商品",
        "tag_category_pic": "",
        "big_pic_url": "",
        "current_page": 0,
        "selected": 0,
        "product_count": 13,
        "description": "超过限购份数可原价购买",
        "sequence": 1,
        "name": "新生儿科",
        "activity_info": {
          "icon_url": "",
          "scheme_url": "",
          "activity_text": ""
        },
        "spus": [{
          "log_field": {
            "recommend_label_type": 0,
            "product_label_type_list": []
          },
          "video_icon": "",
          "status_description": "",
          "tag": "75531876",
          "recommend_description": "",
          "month_saled_content": "周一、周二、周三、周五、周六全天",
          "promotion": {
            "height": 0,
            "width": 0,
            "sku_info_color": "",
            "label_pic": "",
            "promotion_text": "9.33折"
          },
          "product_label_picture_list": [],
          "food_label_text": "",
          "id": 1033063748,
          "min_price": 5.6,
          "description": "主任医师",
          "attrs": [],
          "activity_policy": {
            "discount_by_count": {
              "count": 0,
              "discount": 1.0
            }
          },
          "name": "鲁格兰",
          "praise_num": 2,
          "activity_type": 1,
          "praise_content": "赞2",
          "praise_num_new": 2,
          "activity_tag": "discount",
          "status": 0,
          "mport_sell_status": 0,
          "month_saled": 110,
          "label_text": "",
          "sku_label": "规格",
          "realStatus": 0,
          "promotion_info": "9.33折",
          "virtualStatus": 0,
          "picture": "http://p0.meituan.net/wmproduct/4d84237d5ee088923322e117db816aaa2140995.jpg",
          "unit": "份",
          "tread_num": 1,
          "shippingTimeX": "",
          "sequence": 0,
          "status_remind_list": [],
          "product_label_picture": "",
          "skus": [{
            "spec": "",
            "real_stock": 9832,
            "origin_price": 6.0,
            "status": 0,
            "promotion": {
              "height": 0,
              "width": 0,
              "sku_info_color": "",
              "label_pic": "",
              "promotion_text": "9.33折"
            },
            "promotion_info": "9.33折",
            "box_num": 1.0,
            "restrict": 0,
            "id": 1136715319,
            "picture": "http://p0.meituan.net/wmproduct/4d84237d5ee088923322e117db816aaa2140995.jpg",
            "stock": 9832,
            "price": 5.6,
            "description": "",
            "activity_stock": 9832,
            "min_order_count": 1,
            "box_price": 0.5
          }],
          "share_tip": {
            "share_button_icon": "",
            "activity_id": 0,
            "share_info": {
              "content": "",
              "icon": "",
              "title": "",
              "weixin_url": "",
              "url": ""
            },
            "description": "",
            "description_icon": "",
            "channels": []
          },
          "friends_nickname_praise_content": "",
          "food_label_pic": "",
          "activity_tag_id": "act_17_17",
          "friends_praise_content": ""
        }],
        "buzType": 0
      }, {
        "tags": [],
        "activity_tag": "",
        "icon": "",
        "tag": "69914393",
        "has_next_page": true,
        "type": 1,
        "tag_description": "",
        "tag_category_pic": "",
        "big_pic_url": "",
        "current_page": 0,
        "selected": 0,
        "product_count": 10,
        "description": "",
        "sequence": 2,
        "name": "皮肤科",
        "activity_info": {
          "icon_url": "",
          "scheme_url": "",
          "activity_text": ""
        },
        "spus": [{
          "log_field": {
            "recommend_label_type": 0,
            "product_label_type_list": []
          },
          "video_icon": "",
          "status_description": "",
          "tag": "69914393",
          "recommend_description": "",
          "month_saled_content": "门诊时间：周二、周六全天",
          "promotion": {
            "height": 0,
            "width": 0,
            "sku_info_color": "",
            "label_pic": "",
            "promotion_text": ""
          },
          "product_label_picture_list": [],
          "food_label_text": "",
          "id": 1024489225,
          "min_price": 0.0,
          "description": "主治医师",
          "attrs": [],
          "activity_policy": {
            "discount_by_count": {
              "count": 0,
              "discount": 1.0
            }
          },
          "name": "刘晓凤",
          "praise_num": 0,
          "activity_type": 0,
          "praise_content": "赞0",
          "praise_num_new": 0,
          "activity_tag": "",
          "status": 0,
          "mport_sell_status": 0,
          "month_saled": 4,
          "label_text": "",
          "sku_label": "规格",
          "realStatus": 0,
          "promotion_info": "",
          "virtualStatus": 0,
          "picture": "http://p1.meituan.net/wmproduct/02e61146a7e9cca924347b7280815c4a352861.jpg",
          "unit": "份",
          "tread_num": 1,
          "shippingTimeX": "",
          "sequence": 0,
          "status_remind_list": [],
          "product_label_picture": "",
          "skus": [{
            "spec": "",
            "real_stock": 10000,
            "origin_price": 0.0,
            "status": 0,
            "promotion": {
              "height": 0,
              "width": 0,
              "sku_info_color": "",
              "label_pic": "",
              "promotion_text": ""
            },
            "promotion_info": "",
            "box_num": 1.0,
            "restrict": 0,
            "id": 1126369174,
            "picture": "http://p1.meituan.net/wmproduct/02e61146a7e9cca924347b7280815c4a352861.jpg",
            "stock": 10000,
            "price": 0.0,
            "description": "",
            "activity_stock": 0,
            "min_order_count": 1,
            "box_price": 0.0
          }],
          "share_tip": {
            "share_button_icon": "",
            "activity_id": 0,
            "share_info": {
              "content": "",
              "icon": "",
              "title": "",
              "weixin_url": "",
              "url": ""
            },
            "description": "",
            "description_icon": "",
            "channels": []
          },
          "friends_nickname_praise_content": "",
          "food_label_pic": "",
          "activity_tag_id": "",
          "friends_praise_content": ""
        }],
        "buzType": 0
      }, {
        "tags": [],
        "activity_tag": "",
        "icon": "",
        "tag": "61355880",
        "has_next_page": true,
        "type": 1,
        "tag_description": "",
        "tag_category_pic": "",
        "big_pic_url": "",
        "current_page": 0,
        "selected": 0,
        "product_count": 5,
        "description": "",
        "sequence": 3,
        "name": "儿内科",
        "activity_info": {
          "icon_url": "",
          "scheme_url": "",
          "activity_text": ""
        },
        "spus": [{
          "log_field": {
            "recommend_label_type": 0,
            "product_label_type_list": []
          },
          "video_icon": "",
          "status_description": "",
          "tag": "61355880",
          "recommend_description": "",
          "month_saled_content": "月售1",
          "promotion": {
            "height": 0,
            "width": 0,
            "sku_info_color": "",
            "label_pic": "",
            "promotion_text": ""
          },
          "product_label_picture_list": [],
          "food_label_text": "",
          "id": 1023864070,
          "min_price": 0.0,
          "description": "主任医师",
          "attrs": [],
          "activity_policy": {
            "discount_by_count": {
              "count": 0,
              "discount": 1.0
            }
          },
          "name": "备注需求，请写三遍哦，重要的事情说三遍哟",
          "praise_num": 0,
          "activity_type": 0,
          "praise_content": "赞0",
          "praise_num_new": 0,
          "activity_tag": "",
          "status": 0,
          "mport_sell_status": 0,
          "month_saled": 1,
          "label_text": "",
          "sku_label": "规格",
          "realStatus": 0,
          "promotion_info": "",
          "virtualStatus": 0,
          "picture": "http://p1.meituan.net/wmproduct/df220e91c9b8692daf499c31f28488f4344882.jpg",
          "unit": "份",
          "tread_num": 0,
          "shippingTimeX": "",
          "sequence": 0,
          "status_remind_list": [],
          "product_label_picture": "",
          "skus": [{
            "spec": "",
            "real_stock": 10000,
            "origin_price": 0.0,
            "status": 0,
            "promotion": {
              "height": 0,
              "width": 0,
              "sku_info_color": "",
              "label_pic": "",
              "promotion_text": ""
            },
            "promotion_info": "",
            "box_num": 1.0,
            "restrict": 0,
            "id": 1126228104,
            "picture": "http://p1.meituan.net/wmproduct/df220e91c9b8692daf499c31f28488f4344882.jpg",
            "stock": 10000,
            "price": 0.0,
            "description": "",
            "activity_stock": 0,
            "min_order_count": 1,
            "box_price": 0.0
          }],
          "share_tip": {
            "share_button_icon": "",
            "activity_id": 0,
            "share_info": {
              "content": "",
              "icon": "",
              "title": "",
              "weixin_url": "",
              "url": ""
            },
            "description": "",
            "description_icon": "",
            "channels": []
          },
          "friends_nickname_praise_content": "",
          "food_label_pic": "",
          "activity_tag_id": "",
          "friends_praise_content": ""
        }],
        "buzType": 0
      }, {
        "tags": [],
        "activity_tag": "",
        "icon": "",
        "tag": "61345968",
        "has_next_page": true,
        "type": 1,
        "tag_description": "",
        "tag_category_pic": "",
        "big_pic_url": "",
        "current_page": 0,
        "selected": 0,
        "product_count": 11,
        "description": "",
        "sequence": 4,
        "name": "呼吸/咳喘",
        "activity_info": {
          "icon_url": "",
          "scheme_url": "",
          "activity_text": ""
        },
        "spus": [{
          "log_field": {
            "recommend_label_type": 0,
            "product_label_type_list": []
          },
          "video_icon": "",
          "status_description": "",
          "tag": "61345968",
          "recommend_description": "",
          "month_saled_content": "月售0",
          "promotion": {
            "height": 0,
            "width": 0,
            "sku_info_color": "",
            "label_pic": "",
            "promotion_text": ""
          },
          "product_label_picture_list": [],
          "food_label_text": "",
          "id": 1009949719,
          "min_price": 0.0,
          "description": "",
          "attrs": [],
          "activity_policy": {
            "discount_by_count": {
              "count": 0,
              "discount": 1.0
            }
          },
          "name": "亲，薯条外卖送餐时间较长，口感可能会受到影响，望见谅！",
          "praise_num": 0,
          "activity_type": 0,
          "praise_content": "赞0",
          "praise_num_new": 0,
          "activity_tag": "",
          "status": 0,
          "mport_sell_status": 0,
          "month_saled": 0,
          "label_text": "",
          "sku_label": "规格",
          "realStatus": 0,
          "promotion_info": "",
          "virtualStatus": 0,
          "picture": "http://p0.meituan.net/wmproduct/c9afad85fcae46deffcbc1d218eb26bd181389.jpg",
          "unit": "份",
          "tread_num": 0,
          "shippingTimeX": "",
          "sequence": 0,
          "status_remind_list": [],
          "product_label_picture": "",
          "skus": [{
            "spec": "",
            "real_stock": -1,
            "origin_price": 0.0,
            "status": 0,
            "promotion": {
              "height": 0,
              "width": 0,
              "sku_info_color": "",
              "label_pic": "",
              "promotion_text": ""
            },
            "promotion_info": "",
            "box_num": 1.0,
            "restrict": 0,
            "id": 1110726086,
            "picture": "http://p0.meituan.net/wmproduct/c9afad85fcae46deffcbc1d218eb26bd181389.jpg",
            "stock": 0,
            "price": 0.0,
            "description": "",
            "activity_stock": 0,
            "min_order_count": 1,
            "box_price": 0.0
          }],
          "share_tip": {
            "share_button_icon": "",
            "activity_id": 0,
            "share_info": {
              "content": "",
              "icon": "",
              "title": "",
              "weixin_url": "",
              "url": ""
            },
            "description": "",
            "description_icon": "",
            "channels": []
          },
          "friends_nickname_praise_content": "",
          "food_label_pic": "",
          "activity_tag_id": "",
          "friends_praise_content": ""
        }],
        "buzType": 0
      }],
      "poi_notifications": [],
      "has_hotsale_tag": false,
      "container_operation_source": {
        "poi_coupon_list": [],
        "operation_source_list": [],
        "tag_icon": "http://p1.meituan.net/aichequan/aa78dd5220590e0f2f44c8c9087de9171414.png",
        "tag": "op0020",
        "tag_name": "专场",
        "tag_sequence": 1
      }
    },
    "code": 0,
    "msg": "成功"
  },
  commentData: {
    "data": {
      "avg_ship_time": 10,
      "buz_code": 0,
      "comment_categories": ["全部2188", "有图评价109", "好评2045", "差评92"],
      "comment_num": 2188,
      "comment_praise_ratio": 92,
      "comment_score": 4.5,
      "comment_score_type_infos": [{
        "comment_score_type": 0,
        "total_count": 2188
      }, {
        "comment_score_type": 5,
        "total_count": 109
      }, {
        "comment_score_type": 1,
        "total_count": 2045
      }, {
        "comment_score_type": 3,
        "total_count": 92
      }],
      "comment_tip": "",
      "comments": [{
        "add_comment_list": [{
          "content": "抱歉，错送的问题我们承担大部分责任，给您错送的餐品您请享用。希望可以联系到您，小店将为您补送一次正确的餐品！",
          "desc": "商家回复(2天后)",
          "time": 1537839704,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "点了一个套餐，一个鸡腿变汉堡，我都无语了…",
        "comment_labels": [],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/fdda35443288d4b6ecbe31d5c563229946284.jpg"
        }],
        "comment_scheme": [{
          "keyword": "香酥鸡腿+奥尔良烤翅+老北京鸡肉卷",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=911802422&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1217125460",
          "sku_id": 1217125460,
          "spu_id": 911802422
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537632000,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537632000,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "抱歉，错送的问题我们承担大部分责任，给您错送的餐品您请享用。希望可以联系到您，小店将为您补送一次正确的餐品！",
        "praise_food_list": [{
          "name": "无骨鸡柳",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747118877&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1124829081"
        }, {
          "name": "香酥鸡腿+奥尔良烤翅+老北京鸡肉卷",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=911802422&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1217125460"
        }],
        "praise_food_tip": "无骨鸡柳,香酥鸡腿+奥尔良烤翅+老北京鸡肉卷",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 36,
        "user_id": 1950018823,
        "user_name": "ics781680823",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2051781563
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，感谢您选择品尝本店的美食，谢谢您认可我们的口味和服务，我们会继续努力，为您提供更好的服务。祝您生活愉快！",
          "desc": "商家回复(2天后)",
          "time": 1537839547,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "这个店的汉堡挺好的  也试过其他家的，都没有正新汉堡的好吃！非常喜欢，加油！",
        "comment_labels": [],
        "comment_pics": [],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537632000,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537632000,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，感谢您选择品尝本店的美食，谢谢您认可我们的口味和服务，我们会继续努力，为您提供更好的服务。祝您生活愉快！",
        "praise_food_list": [{
          "name": "香辣鸡腿堡+老北京鸡肉卷+饮料",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=893283581&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=970982145"
        }, {
          "name": "劲脆虾堡",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747123774&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821937"
        }],
        "praise_food_tip": "香辣鸡腿堡+老北京鸡肉卷+饮料,劲脆虾堡",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 28,
        "user_id": 1401915721,
        "user_name": "QqG162355733",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2052228100
      }, {
        "add_comment_list": [{
          "content": "非常荣幸能够得到您的青睐和认可，真的很开心，您的支持和厚爱是对我们最大的肯定",
          "desc": "商家回复(1天后)",
          "time": 1536651710,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "很喜欢这个套餐 好吃哦 尤其是甜奶 真的好好好好喝 真爱了#香辣鸡腿堡+鸡米花+饮料#",
        "comment_labels": [{
          "content": "穿戴工服",
          "label_type": 1
        }, {
          "content": "风雨无阻",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }, {
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "仪表整洁",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/9fe38ca1d69d48e3c80b5d04a04e9106210233.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/be27ef229bbd243e652e2dbd28638f45195858.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/98e758b2391a6490d510e18aa9fa71d6130959.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/e141417478cb880c640ae2d5e8d7b071263669.jpg"
        }],
        "comment_scheme": [{
          "keyword": "香辣鸡腿堡+鸡米花+饮料",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=893326477&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1217087772",
          "sku_id": 1217087772,
          "spu_id": 893326477
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536508800,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536508800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "非常荣幸能够得到您的青睐和认可，真的很开心，您的支持和厚爱是对我们最大的肯定",
        "praise_food_list": [{
          "name": "香辣鸡腿堡+鸡米花+饮料",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=893326477&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1217087772"
        }],
        "praise_food_tip": "香辣鸡腿堡+鸡米花+饮料",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 30,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2025260012
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，非常抱歉影响您的用餐，感谢您的提醒与反馈，您反馈的问题我们会在下次服务中改进，期待您再次的光临！",
          "desc": "商家回复(5天后)",
          "time": 1536030191,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "鸡排肉没以前厚了 炸的也有点老  可乐没有气 就是糖水 不是很满意",
        "comment_labels": [{
          "content": "仪表整洁",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }, {
          "content": "穿戴工服",
          "label_type": 1
        }, {
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/22853911aa75c0fbea2ad07bdd52354177666.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/4dcd00354336cdae4553ea71cea7f922249777.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/197b9f9ab62dcf0702ae9c3a8e023cfa232398.jpg"
        }],
        "comment_scheme": [{
          "keyword": "可乐（大杯）",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=896335846&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=974362156",
          "sku_id": 974362156,
          "spu_id": 896335846
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1535558400,
        "comment_type": 4,
        "critic_food_tip": "可乐（大杯）,正新鸡排（甘梅味）",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1535558400,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，非常抱歉影响您的用餐，感谢您的提醒与反馈，您反馈的问题我们会在下次服务中改进，期待您再次的光临！",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 29,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2002411560
      }, {
        "add_comment_list": [{
          "content": "哈哈，我一般都很低调的，如果你非想夸我的话，来吧北鼻，康忙！",
          "desc": "商家回复(2天后)",
          "time": 1536286777,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "好吃好吃好吃好好吃 甜奶超级无敌好喝！！！！！！",
        "comment_labels": [{
          "content": "风雨无阻",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }, {
          "content": "仪表整洁",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }, {
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "穿戴工服",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/e555b77142186f0d40c5cfdffb82bc8a109230.jpg"
        }],
        "comment_scheme": [{
          "keyword": "甜奶",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747120862&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=974344525",
          "sku_id": 974344525,
          "spu_id": 747120862
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536076800,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536076800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "哈哈，我一般都很低调的，如果你非想夸我的话，来吧北鼻，康忙！",
        "praise_food_list": [{
          "name": "香辣鸡排（香辣味）",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750763135&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813753751"
        }, {
          "name": "劲脆鸡米花",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747118878&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821940"
        }, {
          "name": "甜奶",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747120862&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=974344525"
        }],
        "praise_food_tip": "香辣鸡排（香辣味）,劲脆鸡米花,甜奶",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 27,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2015265338
      }, {
        "add_comment_list": [{
          "content": "宇宙的中心很大，大到可以装下一万种委屈。宇宙的中心很小，小到一份品质外卖就可以让你满足，还温暖了我的心。出门在外，一定记得好好吃饭~",
          "desc": "商家回复(2天后)",
          "time": 1535440868,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "汉堡包很香，好吃。\n鸡排也不错，香香辣辣的，虽然量不多，不过每个吃一点也够了。\n甜牛奶是热的，很好，不过奶味不够浓啊，下次多加点牛奶吧。",
        "comment_labels": [{
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "穿戴工服",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }, {
          "content": "风雨无阻",
          "label_type": 1
        }, {
          "content": "仪表整洁",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/e9374bc57fc01d71d1a5f931cd76746a38044.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/c8245d69a518e9b7db7516291c22352e40445.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/d80535f08608ae5ee55c79d88382ea7138422.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1535212800,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 4,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1535212800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "宇宙的中心很大，大到可以装下一万种委屈。宇宙的中心很小，小到一份品质外卖就可以让你满足，还温暖了我的心。出门在外，一定记得好好吃饭~",
        "praise_food_list": [{
          "name": "正新欢乐吃鸡套餐",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=1033348276&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1136594373"
        }],
        "praise_food_tip": "正新欢乐吃鸡套餐",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 47,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 1992632286
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
          "desc": "商家回复(2天后)",
          "time": 1535091284,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "上次反馈了没竹签的问题，这次有了，味道好！就是饮料略显单薄啊…",
        "comment_labels": [],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/17aa3d81c425af6f791cd1731785701729494.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/a46da3ab88d389974d927836e12da2e321494.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1534867200,
        "comment_type": 4,
        "critic_food_tip": "果珍",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 4,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1534867200,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
        "praise_food_list": [{
          "name": "香辣鸡排（香辣味）",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750763135&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813753751"
        }, {
          "name": "香辣鸡腿堡",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747123773&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809829128"
        }],
        "praise_food_tip": "香辣鸡排（香辣味）,香辣鸡腿堡",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 59,
        "user_id": 1411341042,
        "user_name": "RhF260850500",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 1982738507
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
          "desc": "商家回复(2天后)",
          "time": 1537839572,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "这个鸡排对我充满恶意，块头太大了😂",
        "comment_labels": [{
          "content": "穿戴工服",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }, {
          "content": "风雨无阻",
          "label_type": 1
        }, {
          "content": "仪表整洁",
          "label_type": 1
        }, {
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/e6c3e4fb9c629ea4f75f364732feeb16353001.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537632000,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537632000,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
        "praise_food_list": [{
          "name": "老北京鸡肉卷",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747128142&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821936"
        }, {
          "name": "正新鸡排（孜然味）",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750759539&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813756291"
        }],
        "praise_food_tip": "老北京鸡肉卷,正新鸡排（孜然味）",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 21,
        "user_id": 263016208,
        "user_name": "WangZR0915",
        "user_pic_url": "https://img.meituan.net/avatar/066635647c345bb0a6e0689e816005c411513.jpg",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2052086086
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
          "desc": "商家回复(1天后)",
          "time": 1534468143,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "这就是13.9的香肠？和图片不一样吧，和正新一样的香肠也就买15，欺骗消费者？",
        "comment_labels": [{
          "content": "风雨无阻",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/dc1b8ff4d1c43f69b4e22307a7d25d92220232.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1534348800,
        "comment_type": 4,
        "critic_food_tip": "正新烤肠一根",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 4,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1534348800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
        "praise_food_list": [{
          "name": "正新鸡排（甘梅味）",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750769349&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813765053"
        }],
        "praise_food_tip": "正新鸡排（甘梅味）",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 50,
        "user_id": 526935004,
        "user_name": "maN522380848",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 1968137641
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
          "desc": "商家回复(3天后)",
          "time": 1534731697,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "鸡肉卷很好吃但是鸡腿堡的肉实在是太老了     老板大半夜还在上班 好评",
        "comment_labels": [{
          "content": "穿戴工服",
          "label_type": 1
        }, {
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "风雨无阻",
          "label_type": 1
        }, {
          "content": "仪表整洁",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }],
        "comment_pics": [],
        "comment_scheme": [{
          "keyword": "香辣鸡腿堡+老北京鸡肉卷+饮料",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=893283581&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=970982145",
          "sku_id": 970982145,
          "spu_id": 893283581
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1534435200,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 5,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1534435200,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
        "praise_food_list": [{
          "name": "香辣鸡腿堡+老北京鸡肉卷+饮料",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=893283581&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=970982145"
        }],
        "praise_food_tip": "香辣鸡腿堡+老北京鸡肉卷+饮料",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 41,
        "user_id": 1316064294,
        "user_name": "白手巨棒",
        "user_pic_url": "https://img.meituan.net/avatar/078ee9b2110111794bce4faa1143dcfb85521.jpg",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 1971705215
      }, {
        "add_comment_list": [{
          "content": "亲爱的客官您好，非常感谢您的反馈，不能让您全部满意，我们深感抱歉，我们一定会采取有效措施针对您提出的建议进行改善，相信有了您的监督我们会做得更好，期待您的再次光临",
          "desc": "商家回复(1天后)",
          "time": 1537255031,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "#骨肉相连#虽然凉了，好在味道还行。#正新鸡排（孜然味）#送到时没有热度了，上面一层水蒸气…一点不好吃…这次很失望…第一次买正新的#无骨鸡柳#，老实说，很难吃，真的。一次失望的用餐体验……",
        "comment_labels": [{
          "content": "风雨无阻",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/34fe47b560f18a854d06c653740490e966235.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/cc3ec23c8a7cdaee3e7c0c4cd2b2474a49958.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/f602537496618d83cb7529adcdf2dae737630.jpg"
        }],
        "comment_scheme": [{
          "keyword": "正新鸡排（孜然味）",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750759539&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813756291",
          "sku_id": 813756291,
          "spu_id": 750759539
        }, {
          "keyword": "骨肉相连",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747118875&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1125018639",
          "sku_id": 1125018639,
          "spu_id": 747118875
        }, {
          "keyword": "无骨鸡柳",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747118877&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1124829081",
          "sku_id": 1124829081,
          "spu_id": 747118877
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537113600,
        "comment_type": 4,
        "critic_food_tip": "正新鸡排（孜然味）,骨肉相连,无骨鸡柳",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537113600,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的客官您好，非常感谢您的反馈，不能让您全部满意，我们深感抱歉，我们一定会采取有效措施针对您提出的建议进行改善，相信有了您的监督我们会做得更好，期待您的再次光临",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 35,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2039920173
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客您好，每个人的口味都不一样，我们店里的东西我们自己员工餐自己都在吃，我不知道你出于何种目的这样说，我是本店店长，如果你有什么不满都可来本店对质，我们店位于龙茗路1689号，祝亲生活愉快",
          "desc": "商家回复(1天后)",
          "time": 1537180681,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "看到很多差评，但是没在意还是点了，结果真的是难吃，汉堡牛肉太腥，鸡肉卷里面的肉不说了，鸡腿不说了......不想点第二次的店",
        "comment_labels": [],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/f524e08f5bfae49398d2f7faa5dad98344496.jpg"
        }],
        "comment_scheme": [{
          "keyword": "老北京鸡肉卷",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747128142&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821936",
          "sku_id": 809821936,
          "spu_id": 747128142
        }, {
          "keyword": "特价 香酥鸡腿",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=1033063748&wmpoiid=470871157426160&sputag=&activitytag=discount&sku_id=1136715319",
          "sku_id": 1136715319,
          "spu_id": 1033063748
        }, {
          "keyword": "牛肉堡",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747120858&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809830064",
          "sku_id": 809830064,
          "spu_id": 747120858
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537027200,
        "comment_type": 4,
        "critic_food_tip": "老北京鸡肉卷,牛肉堡,特价 香酥鸡腿",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537027200,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客您好，每个人的口味都不一样，我们店里的东西我们自己员工餐自己都在吃，我不知道你出于何种目的这样说，我是本店店长，如果你有什么不满都可来本店对质，我们店位于龙茗路1689号，祝亲生活愉快",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 22,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2037090830
      }, {
        "add_comment_list": [],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "#香辣鸡腿堡##老北京鸡肉卷#今天的汉堡和鸡肉卷里面的鸡肉一股味道，咬了一口都吐了，恶心死了！",
        "comment_labels": [],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/51d507f9ddf809ce1c6b5951299360e1417071.jpg"
        }],
        "comment_scheme": [{
          "keyword": "老北京鸡肉卷",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747128142&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821936",
          "sku_id": 809821936,
          "spu_id": 747128142
        }, {
          "keyword": "香辣鸡腿堡",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747123773&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809829128",
          "sku_id": 809829128,
          "spu_id": 747123773
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537286400,
        "comment_type": 4,
        "critic_food_tip": "香辣鸡腿堡,老北京鸡肉卷,无骨鸡柳",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537286400,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 46,
        "user_id": 206263253,
        "user_name": "RXR390088979",
        "user_pic_url": "https://img.meituan.net/avatar/f37d9b01b9e7bfddb9e92adf1d8a907764733.jpg",
        "user_poi_comment_num": 1,
        "user_type": 2,
        "wm_comment_id": 2043981905
      }, {
        "add_comment_list": [{
          "content": "尊敬的顾客您好，我们产品的质量每天都是层层把关的，不会存在东西发臭的，我们每天都是腌好卖完，绝不留隔夜产品，感谢亲的光临，祝亲生活愉快",
          "desc": "商家回复(1天后)",
          "time": 1537067922,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "香辣鸡翅没有味我不说什么，臭了！！！鸡翅竟然臭了，恶心死了",
        "comment_labels": [],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/35b7d216c7d29e0930c99a48a0715800281405.jpg"
        }],
        "comment_scheme": [{
          "keyword": "香辣鸡翅",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747128143&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1125645926",
          "sku_id": 1125645926,
          "spu_id": 747128143
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536940800,
        "comment_type": 4,
        "critic_food_tip": "香辣鸡排（香辣味）,香辣鸡腿堡,墨西哥鸡肉卷,香辣鸡翅",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536940800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "尊敬的顾客您好，我们产品的质量每天都是层层把关的，不会存在东西发臭的，我们每天都是腌好卖完，绝不留隔夜产品，感谢亲的光临，祝亲生活愉快",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 37,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2035936845
      }, {
        "add_comment_list": [{
          "content": "亲爱的客官您好，非常感谢您的反馈，不能让您全部满意，我们深感抱歉，我们一定会采取有效措施针对您提出的建议进行改善，相信有了您的监督我们会做得更好，期待您的再次光临",
          "desc": "商家回复(3天后)",
          "time": 1537256570,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "味道真心不好吃，没有味道，香辣鸡腿堡不辣，薯条搞的黑黢黢的，没有食欲，2",
        "comment_labels": [],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/ee684b0fa8e887d34ae7e8ed155be70844591.jpg"
        }],
        "comment_scheme": [{
          "keyword": "薯条",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747123775&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1124829235",
          "sku_id": 1124829235,
          "spu_id": 747123775
        }, {
          "keyword": "香辣鸡腿堡",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747123773&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809829128",
          "sku_id": 809829128,
          "spu_id": 747123773
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536940800,
        "comment_type": 4,
        "critic_food_tip": "香辣鸡腿堡,劲脆鸡米花,薯条",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536940800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的客官您好，非常感谢您的反馈，不能让您全部满意，我们深感抱歉，我们一定会采取有效措施针对您提出的建议进行改善，相信有了您的监督我们会做得更好，期待您的再次光临",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 42,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2035042411
      }, {
        "add_comment_list": [{
          "content": "不好意思，下次备注为您补发一份",
          "desc": "商家回复(1天后)",
          "time": 1537066164,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "味道还是很好的 就是我要的热奶怎么给我送的果汁？？",
        "comment_labels": [{
          "content": "货品完好",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/4b4514acf8e429404d097fc35c2cd036131756.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536940800,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 3,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536940800,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "不好意思，下次备注为您补发一份",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 39,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2035252988
      }, {
        "add_comment_list": [],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "你开玩笑？我点了两份去骨鸡柳，你就送了一份。什么意思？",
        "comment_labels": [{
          "content": "快速准时",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/533b71d769fe5336f210ad7379b305c0257846.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537459200,
        "comment_type": 4,
        "critic_food_tip": "香辣鸡排+无骨鸡柳+黑椒鸡块+饮料,无骨鸡柳",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537459200,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 31,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2048506232
      }, {
        "add_comment_list": [{
          "content": "抱歉，漏送是我们不对，下次备注一下为您补发一份，真心抱歉",
          "desc": "商家回复(1天后)",
          "time": 1536890262,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "甜奶呢？其他都好，就是少东西",
        "comment_labels": [{
          "content": "礼貌热情",
          "label_type": 1
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/89dc6a29d4cb66b30dfedf4c22f7490d85298.jpg"
        }],
        "comment_scheme": [{
          "keyword": "甜奶",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747120862&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=974344525",
          "sku_id": 974344525,
          "spu_id": 747120862
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536768000,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 3,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536768000,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "抱歉，漏送是我们不对，下次备注一下为您补发一份，真心抱歉",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 42,
        "user_id": 230794447,
        "user_name": "Vmz729512894",
        "user_pic_url": "https://img.meituan.net/avatar/3154b744737f2a2af25e4bab07a173e736444.jpg",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2031430217
      }, {
        "add_comment_list": [{
          "content": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
          "desc": "商家回复(2天后)",
          "time": 1537066411,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "老北京鸡肉卷没吃就老北京味。。。感觉和墨西哥鸡肉卷一个味。鸡柳非常难吃，非常。鸡排还可以。",
        "comment_labels": [{
          "content": "货品完好",
          "label_type": 1
        }],
        "comment_pics": [],
        "comment_scheme": [{
          "keyword": "无骨鸡柳",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747118877&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=1124829081",
          "sku_id": 1124829081,
          "spu_id": 747118877
        }, {
          "keyword": "正新鸡排（甘梅味）",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750769349&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813765053",
          "sku_id": 813765053,
          "spu_id": 750769349
        }, {
          "keyword": "老北京鸡肉卷",
          "scheme_url": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747128142&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821936",
          "sku_id": 809821936,
          "spu_id": 747128142
        }],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536854400,
        "comment_type": 4,
        "critic_food_tip": "无骨鸡柳",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 3,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536854400,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "亲爱的顾客，十分抱歉本次的服务没有让您获得最佳体验，我们会不断改善服务，期待您的再次惠顾！",
        "praise_food_list": [{
          "name": "正新鸡排（甘梅味）",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=750769349&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=813765053"
        }, {
          "name": "老北京鸡肉卷",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747128142&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809821936"
        }],
        "praise_food_tip": "正新鸡排（甘梅味）,老北京鸡肉卷",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 33,
        "user_id": 6358760,
        "user_name": "fancy0104",
        "user_pic_url": "https://img.meituan.net/avatar/15d36659cfdff1b4412fac91e904cf4e33310.jpg",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2033508380
      }, {
        "add_comment_list": [{
          "content": "抱歉，下次一定注意，甜奶热的口感更好哦",
          "desc": "商家回复(1天后)",
          "time": 1536890308,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "大哥我也是服了，我备注了三遍凉的牛奶，还是热的，能长点心吗",
        "comment_labels": [{
          "content": "礼貌热情",
          "label_type": 1
        }, {
          "content": "快速准时",
          "label_type": 1
        }, {
          "content": "货品完好",
          "label_type": 1
        }, {
          "content": "风雨无阻",
          "label_type": 1
        }, {
          "content": "穿戴工服",
          "label_type": 1
        }, {
          "content": "仪表整洁",
          "label_type": 1
        }],
        "comment_pics": [],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1536768000,
        "comment_type": 4,
        "critic_food_tip": "甜奶",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 0,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 3,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1536768000,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "抱歉，下次一定注意，甜奶热的口感更好哦",
        "praise_food_list": [{
          "name": "香辣鸡腿堡",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747123773&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809829128"
        }, {
          "name": "牛肉堡",
          "schema_uri": "meituanwaimai://waimai.meituan.com/detail?buztype=0&spuid=747120858&wmpoiid=470871157426160&sputag=&activitytag=&sku_id=809830064"
        }],
        "praise_food_tip": "香辣鸡腿堡,牛肉堡",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 31,
        "user_id": 1420425413,
        "user_name": "hja816427182",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2031414781
      }, {
        "add_comment_list": [{
          "content": "餐骑手给你送到了，你也确认收货了，然后又申请退款，餐也损失了，钱也退你了，请问这位亲，你还想要哪样呢",
          "desc": "商家回复(1天后)",
          "time": 1537253440,
          "type": 2
        }],
        "buz_code": 0,
        "can_additional": 1,
        "comment": "11.31叫的 13点才送过来  要求退款 爱理不理 拒绝退款 美团客服退的款 🌚",
        "comment_labels": [{
          "content": "配送慢",
          "label_type": 2
        }],
        "comment_pics": [{
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/e6d7dde08bc4d4bde342b878021627d711691.jpg"
        }, {
          "thumbnail_url": "",
          "url": "http://p0.meituan.net/wmcomment/022022c557952c4294912251e29ae5c420962.jpg"
        }],
        "comment_scheme": [],
        "comment_source_tip": "",
        "comment_source_type": 3,
        "comment_time": 1537113600,
        "comment_type": 4,
        "critic_food_tip": "",
        "delivery_comment_score": 0,
        "delivery_name": "",
        "delivery_type": 0,
        "disable_additional_msg": "",
        "food_comment_score": 0,
        "has_add_comment": false,
        "high_quality": 0,
        "is_anonymous": 1,
        "is_dp": 0,
        "is_picture_audited": false,
        "order_comment_score": 1,
        "order_detail": {
          "order_detail_list": [],
          "order_view_id": 0,
          "total_price": 0.0
        },
        "order_time": 1537113600,
        "order_type": 1,
        "pack_score": 0,
        "poi_id": 0,
        "poi_reply_contents": "餐骑手给你送到了，你也确认收货了，然后又申请退款，餐也损失了，钱也退你了，请问这位亲，你还想要哪样呢",
        "praise_food_list": [],
        "praise_food_tip": "",
        "quality_score": 0,
        "scheme": "",
        "ship_score": 0.0,
        "ship_time": 88,
        "user_id": 0,
        "user_name": "匿名用户",
        "user_pic_url": "",
        "user_poi_comment_num": 1,
        "user_type": 0,
        "wm_comment_id": 2039360400
      }],
      "comments_dp": {
        "comment_score": 3.5,
        "comments": [],
        "dp_poi_id": 98954344,
        "show": 1,
        "title": "大众点评",
        "total_count_desc": "13条到店评价",
        "wm_poi_id": 470871157426160
      },
      "delivery_score": 4.8,
      "filter_type_num": 2188,
      "food_score": 4.5,
      "friend_status_banner": {
        "bind_schema": "meituanwaimai://waimai.meituan.com/bindfriend?from=3",
        "friend_status": 1,
        "friend_status_tip": ""
      },
      "has_more": true,
      "labels": [{
        "content": "味道赞",
        "label_count": 76,
        "label_id": 75,
        "label_star": 5
      }, {
        "content": "价格实惠",
        "label_count": 16,
        "label_id": 61,
        "label_star": 5
      }, {
        "content": "满意",
        "label_count": 14,
        "label_id": 34,
        "label_star": 5
      }, {
        "content": "包装好",
        "label_count": 11,
        "label_id": 29,
        "label_star": 5
      }, {
        "content": "分量足",
        "label_count": 9,
        "label_id": 50,
        "label_star": 5
      }, {
        "content": "推荐",
        "label_count": 8,
        "label_id": 36,
        "label_star": 5
      }],
      "pack_score": 4.5,
      "quality_score": 4.5,
      "scores": {
        "comment_score": 0.0,
        "delivery_score": 0.0,
        "pack_score": 0.0,
        "quality_score": 0.0,
        "show": 0
      }
    },
    "code": 0,
    "msg": "成功"
  },
  shopInfo: {}
}

export {shoppingCart}