const homeData = {
  headData: {
    "data": {
      "across_banner_list": [],
      "bid_banner_list": [],
      "bubble_max_num": 16,
      "card_list": [],
      "friend_feeds": {
        "feed_list": [],
        "logo": ""
      },
      "kingkong_bg_image": "",
      "kingkong_font_color": "",
      "new_user_task": {
        "bg_url": "",
        "click_url": "",
        "icon_url": "",
        "left_text": "",
        "right_text": ""
      },
      "primary_filter": [{
        "brand_type": -1,
        "code": 910,
        "first_tag_codes": [],
        "gray_switch": 0,
        "gray_url": "http://p0.meituan.net/jungle/6539a4c1d2bb51b572e399016ee0e8cb11261.png",
        "method": 1258576,
        "name": "美食",
        "second_tag_codes": [],
        "sequence": 100,
        "skip_protocol": "channel?category_type=910&category_text=%E7%BE%8E%E9%A3%9F",
        "url": "http://p1.meituan.net/jungle/8b5e1702d4145ccf058ba5fb31008c5310912.png"
      }],
      "recommended_search_keyword": {
        "scene_type": "NORMAL",
        "search_keyword": "米粉",
        "tgt_stids": "",
        "type": 1,
        "view_keyword": "米粉"
      },
      "supermarket_scan": {
        "scan_support": 0,
        "scheme_url": ""
      },
      "tgtStidMap": {},
      "top_banner_list": [],
      "user_task": {
        "bg_url": "",
        "button_text": "",
        "click_url": "",
        "icon_url": "",
        "left_highlight": "",
        "left_text": "",
        "right_text": "",
        "task_id": 0,
        "task_type": 0
      }
    },
    "code": 0,
    "msg": "成功"
  },
  homeList: {
    "tgt_stids": "",
    "data": {
      "activity_id": 0,
      "activity_type": 0,
      "boldingList": [],
      "coupon_nologin_background": "",
      "footprint_entrance": {
        "icon_url": "http://p1.meituan.net/aichequan/6dd136c9612331817f952475d749770b4238.png",
        "is_show": true
      },
      "has_activity": false,
      "judas_field": {
        "rank_trace_id": "187AD74976B0B1452CF9343BDDBA2720"
      },
      "need_login": false,
      "poi_has_next_page": true,
      "poi_total_num": 3325,
      "poilist": [{
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=17&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=974877&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=5&act_lng=121380753&userId=228577344&shopThirdType=154&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=974877&shop_id=974877&rmp=94jsS6z2kwQHT5uvywnWEXLl_plwzN6ik-S8f_x6oJ-O&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=974877&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=974877&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_4",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "30分钟",
        "delivery_type": 0,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：0571-89776699 ",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 杭州市江干区景昙路9号西子国际大厦T3B座1303、1304室",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "诊疗费、检查费6折（齿科、眼科、耗材及药品费用除外）",
          "promotion_type": 2
        }],
        "distance": "897m",
        "distance_display_control": 0,
        "id": 296912096965757,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "35减21",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "50减31",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "75减41",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "4.9折起",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减17",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "支持自取",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 2,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 30,
          "poi_type_icon_type": 2,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：周一至周六 9：00-21：00",
        "month_sales_tip": "0条评价",
        "name": "唯尔诺-杭州庆春门诊部",
        "only_self_delivery": 0,
        "origin_nurse": "",
        "pic_url": "/static/clinic/zhensuo5.jpg",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p1.meituan.net/wmproductwm/323f6d9c20cae9d6046d0214865cda9c299487.jpg",
        "poi_type_icon": "http://p1.meituan.net/aichequan/a88918ba8699e15a5d16d5d7e09ad0022192.png",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "西式快餐",
        "trade_area": "万源城/东兰路",
        "wm_poi_score": 4.5
      },{
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境: 5",
        "charge_info": "aor_type=2&shopSecondType=167&kaPlanId=211&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=1032138&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=2&act_lng=121380753&userId=228577344&shopThirdType=0&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=45372977&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=1032138&shop_id=1032138&rmp=OdT1vOYJ8vgEC7AbM12ig-Hz_Po2vnC1wOGDiUWkKchp&ins=target_id%40ad%40plan_id%40account_id&isKa=true&target_id=1032138&shopType=19&request_id=70612337&appVersion=3.1.0&ad=1032138&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_1",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "35分钟",
        "delivery_type": 1,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：020-83362088",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 广州市越秀区环市东路422号庄地铁站A出口星程酒店2楼",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "门诊费用8.5折、筛查类项目8折",
          "promotion_type": 2
        }],
        "distance": "3.8km",
        "distance_display_control": 0,
        "id": 316329644127890,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "45减6",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减17",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }],
        "log_field": {
          "average_delivery_time": 35,
          "poi_type_icon_type": 2,
          "recommend_type": 3,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：9：00-21：00",
        "month_sales_tip": "0条评价",
        "name": "都安全医疗-广州区庄诊所",
        "only_self_delivery": 0,
        "origin_nurse": "¥7",
        "pic_url": "/static/clinic/zhensuo2.png",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p1.meituan.net/wmproductdwm/247aa1b0580f7f567039ffbba5522b8142876.jpg",
        "poi_type_icon": "http://p1.meituan.net/aichequan/a88918ba8699e15a5d16d5d7e09ad0022192.png",
        "rank_label_info": "",
        "recommend_info": {
          "icon": "http://p1.meituan.net/xianfu/a0b192ffdab672109d9f767dbd49653a919.png",
          "recommend_reason": "大众点评高分店铺",
          "type": 3
        },
        "recommend_level_list": [{
          "content_color": "#FF6D27",
          "icon": "",
          "recommend_reason": "点评高分店铺",
          "type": 3
        }],
        "recommend_level_type": 1,
        "recommend_list": [{
          "icon": "http://p1.meituan.net/xianfu/a0b192ffdab672109d9f767dbd49653a919.png",
          "recommend_reason": "点评高分店铺",
          "type": 3
        }],
        "scheme": "",
        "self_delivery_icon": "",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "甜品",
        "trade_area": "南方商城",
        "wm_poi_score": 4.6
      },{
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=15&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=780749&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=4&act_lng=121380753&userId=228577344&shopThirdType=133&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=780749&shop_id=780749&rmp=DKRShAW8bSrVEBmH2kXJ-KlSZYdGprutpS0HbgFa2isu&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=780749&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=780749&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_3",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "30分钟",
        "delivery_type": 1,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：4008935111",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 上海浦东新区居家桥595号",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "门诊医疗服务整单9折（药品、血液、耗材、齿科、眼科无折扣）",
          "promotion_type": 2
        }],
        "distance": "1.8km",
        "distance_display_control": 0,
        "id": 341884699482611,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "38减23",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "68减36",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "98减49",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "2.05折起",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "满赠",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减17",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "支持自取",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 2,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 30,
          "poi_type_icon_type": 0,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "周一到周六：8：30-17：30",
        "month_sales_tip": "0条评价",
        "name": "上海艾尔贝佳妇产科医院",
        "only_self_delivery": 0,
        "origin_nurse": "",
        "pic_url": "/static/clinic/zhensuo4.jpg",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p0.meituan.net/xianfudwm/a65419a8eab793dc0515465cc4a7f01c211702.jpg",
        "poi_type_icon": "",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "川湘菜",
        "trade_area": "万源城/东兰路",
        "wm_poi_score": 4.0
      },{
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=10&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=4208203&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=8&act_lng=121380753&userId=228577344&shopThirdType=3003&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=4208203&shop_id=4208203&rmp=k0nrtVTb_vLMGjTREBg1hd0_WxjVYn1iu1JEoGlIj-fi&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=4208203&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=4208203&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_7",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "38分钟",
        "delivery_type": 0,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：400-680-8068 ",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 北京市朝阳区阜通东大街1号院7号楼1层6101室",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "部分6折-7.5折",
          "promotion_type": 2
        }],
        "distance": "2.2km",
        "distance_display_control": 0,
        "id": 371425484576088,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "已领5元券",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 1
        }, {
          "activity_id": 0,
          "content": "25减22",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "58减27",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "88减30",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "118减32",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "有机会领券",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减30",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "极速退款",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 1,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 38,
          "poi_type_icon_type": 0,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：周一至周日：9：00-18：00",
        "month_sales_tip": "0条评价",
        "name": "联合医务-北京望京诊所",
        "only_self_delivery": 0,
        "origin_nurse": "¥3",
        "pic_url": "/static/clinic/zhensuo8.png",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p0.meituan.net/xianfudwm/c176f2fd991bbbdc64388ec36cd7b678100865.jpg",
        "poi_type_icon": "",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "鸡公煲",
        "trade_area": "万源城/东兰路",
        "wm_poi_score": 4.4
      },  {
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=10&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=1047417&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=6&act_lng=121380753&userId=228577344&shopThirdType=94&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=1047417&shop_id=1047417&rmp=CMyk1KwECYENdas9aqPhvoVGCk0Z1WUZ_S1pBXSTv2RC&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=1047417&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=1047417&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_5",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "32分钟",
        "delivery_type": 0,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：400-6808068 ",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 上海市黄浦区济南路9号202单位",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "部分6折-7.5折",
          "promotion_type": 2
        }],
        "distance": "2.6km",
        "distance_display_control": 0,
        "id": 394777221735793,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "22减20",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "50减30",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "80减40",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "4.71折起",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "支持自取",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 2,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }, {
          "activity_id": 0,
          "content": "极速退款",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 1,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 32,
          "poi_type_icon_type": 2,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：周一至周六 9：00-18：00",
        "month_sales_tip": "0条评价",
        "name": "联合医务-上海联合医疗门诊部",
        "only_self_delivery": 0,
        "origin_nurse": "",
        "pic_url": "/static/clinic/zhensuo6.jpg",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p0.meituan.net/wmproduct/f863e002d0489e31122e5f9d7dcf2b61405235.jpg",
        "poi_type_icon": "http://p1.meituan.net/aichequan/a88918ba8699e15a5d16d5d7e09ad0022192.png",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "中式简餐",
        "trade_area": "",
        "wm_poi_score": 4.5
      }, {
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=14&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=1602339&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=9&act_lng=121380753&userId=228577344&shopThirdType=130&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=1602339&shop_id=1602339&rmp=1q9dawckm_flScK8xkUVq-Eu6EWyzhsjIc8hYPzj7QUo&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=1602339&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=1602339&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_8",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "30分钟",
        "delivery_type": 1,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：400-680-8068 ",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 北京市朝阳区东三环中路7号财富中心写字楼A座一层E107",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "部分6折-7.5折",
          "promotion_type": 2
        }],
        "distance": "2.7km",
        "distance_display_control": 0,
        "id": 401838148024129,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "已领28元券",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 1
        }, {
          "activity_id": 0,
          "content": "28减20",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "45减28",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "60减35",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "3.54折起",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "返3元券",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "满赠",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减17",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "新客减1",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "支持自取",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 2,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 30,
          "poi_type_icon_type": 0,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：9：00-21：00",
        "month_sales_tip": "0条评价",
        "name": "联合医务-北京财富诊所",
        "only_self_delivery": 0,
        "origin_nurse": "",
        "pic_url": "/static/clinic/zhensuo9.png",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p1.meituan.net/xianfudwm/02538b119576c59f94e49ef8222ec1e7131575.jpg",
        "poi_type_icon": "",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "麻辣",
        "trade_area": "",
        "wm_poi_score": 4.0
      },{
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=17&kaPlanId=62&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=4460055&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=1&act_lng=121380753&userId=228577344&shopThirdType=154&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=25866913&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=4460055&shop_id=4460055&rmp=6yfiCb8F1SLjDilQzHOx5J_ZzKolFZdY7xHWwRdZXoTt&ins=target_id%40ad%40plan_id%40account_id&isKa=true&target_id=4460055&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=4460055&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_0",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "30分钟",
        "delivery_type": 0,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：400 892 0288",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 上海市浦东新区滨江大道1616号",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "门诊医疗服务整单9折（药品、血液、耗材、齿科、眼科无折扣）",
          "promotion_type": 2
        }],
        "distance": "5.76km",
        "distance_display_control": 0,
        "id": 470871157360624,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "35减23",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "50减33",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "70减43",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "5.93折起",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减17",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "新客减1",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "支持自取",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 2,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 30,
          "poi_type_icon_type": 2,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5 ",
		"business_time": "营业时间：8：00-21：00",
        "month_sales_tip": "1条评价",
        "name": "上海浦滨儿童医院",
        "only_self_delivery": 0,
        "origin_nurse": "¥3",
        "pic_url": "/static/clinic/zhensuo1.png",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p1.meituan.net/wmproduct/acef6c8f22c14ce8e04c1e24ec9de8681498229.jpg",
        "poi_type_icon": "http://p1.meituan.net/aichequan/a88918ba8699e15a5d16d5d7e09ad0022192.png",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
        "nurse": "护士: 4",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "西式快餐",
        "trade_area": "万源城/东兰路",
        "wm_poi_score": 4.5
      }, {
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=176&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=1095312&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=3&act_lng=121380753&userId=228577344&shopThirdType=0&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=1095312&shop_id=1095312&rmp=yCLpT3Htcn39_kVDh4LFSnaVL3RQNl6-XER_itITQvbE&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=1095312&shopType=21&request_id=70612337&appVersion=3.1.0&ad=1095312&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_2",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "34分钟",
        "delivery_type": 0,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": " 预约电话：010-8410 2363",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址：  北京市朝阳区京顺东街6号院2号楼 101-501（北京地坛医院东门对面）",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "Aon专属诊疗套餐或部分5折",
          "promotion_type": 2
        }],
        "distance": "3.2km",
        "distance_display_control": 0,
        "id": 545985840379359,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "38减35",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "68减40",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "98减50",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "158减58",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "268减68",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "1折起",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "有机会领券",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "返1元券",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "满赠",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "买赠",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减17",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "极速退款",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 1,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 34,
          "poi_type_icon_type": 0,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：周一至周六 10：00-18：00",
        "month_sales_tip": "0条评价",
        "name": "北京百汇景顺诊所",
        "only_self_delivery": 0,
        "origin_nurse": "¥5",
        "pic_url": "/static/clinic/zhensuo3.png",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p1.meituan.net/wmproduct/854b2d4c51404a265019b058f97326cf832458.jpg",
        "poi_type_icon": "",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "",
        "trade_area": "七宝",
        "wm_poi_score": 4.5
      },  {
        "ad_attr": "",
        "ad_mark": false,
        "ad_type": 15,
        "environment": "环境：5",
        "charge_info": "aor_type=2&shopSecondType=15&kaPlanId=0&act_lat=31150623&lng=121381110&cityLevel=2&secondLevelCityId=310112&plan_id=1671929&pos=1&user_ip=114.94.126.62&cpsActivityId=2&city_id=310100&adidx=7&act_lng=121380753&userId=228577344&shopThirdType=133&hostName=gh-waimai-d-cpsproperty01.gh.sankuai.com&adType=15&slot=78&kaAcctId=0&bid=0&lat=31150280&aor_id=267594&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=1671929&shop_id=1671929&rmp=hqWqtMEjgf760Pgxghfvq1NqjZNla9MIuDsySE-IbGB5&ins=target_id%40ad%40plan_id%40account_id&isKa=false&target_id=1671929&shopType=1000&request_id=70612337&appVersion=3.1.0&ad=1671929&sver=2&poiApiPageType=1&channel=9&tags=[{\"first_level_type\":2,\"second_level_type\":2,\"name\":\"外卖节\"}]&api_pos=P0_6",
        "closing_tips": "",
        "container_template": {
          "tag_icon": "",
          "type": 0
        },
        "delivery_time_tip": "30分钟",
        "delivery_type": 1,
        "discounts2": [{
          "activity_id": 0,
          "icon_url": "/static/iphone.png",
          "info": "预约电话：400-680-8068 ",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/address.png",
          "info": "诊所地址： 北京市东城区崇文门外大街3号3-27新世界中心五层501号",
          "promotion_type": 2
        }, {
          "activity_id": 0,
          "icon_url": "/static/youhui.png",
          "info": "部分6折-7.5折",
          "promotion_type": 2
        }],
        "distance": "1.2km",
        "distance_display_control": 0,
        "id": 470892632209391,
        "insurance_icon": "",
        "insurance_type": 0,
        "is_favorite": 0,
        "label_info": [{
          "activity_id": 0,
          "content": "35减15",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "78减25",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "108减35",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "首单减22",
          "content_color": "#FB4E44",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#FDC9C6",
          "poi_service_type": 0,
          "priority": 0,
          "priority_sort_index": 0,
          "type": 2
        }, {
          "activity_id": 0,
          "content": "支持自取",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 2,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }, {
          "activity_id": 0,
          "content": "极速退款",
          "content_color": "#15B0A0",
          "icon_url": "",
          "label_background_color": "",
          "label_frame_color": "#B4ECE6",
          "poi_service_type": 1,
          "priority": 1,
          "priority_sort_index": 0,
          "type": 3
        }],
        "log_field": {
          "average_delivery_time": 30,
          "poi_type_icon_type": 0,
          "recommend_type": 0,
          "search_log_id": ""
        },
        "doctor": "医生：5",
		"business_time": "营业时间：周一至周日 8：00-17：00 ",
        "month_sales_tip": "0条评价",
        "name": "联合医务-北京耀东门诊部",
        "only_self_delivery": 0,
        "origin_nurse": "¥4",
        "pic_url": "/static/clinic/zhensuo7.png",
        "poi_promotion_pic": "http://p1.meituan.net/scarlett/e8efc66f0186abf3415ec87df10ae4d07007.png",
        "poi_recommend_pic_url": "http://p1.meituan.net/wmproductdwm/19d8949ceefa4deb374f40ae6af960c8154221.jpg",
        "poi_type_icon": "",
        "rank_label_info": "",
        "recommend_level_type": 0,
        "scheme": "",
        "self_delivery_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
        "nurse": "护士: 5",
        "status": 1,
        "status_desc": "",
        "story_icon": "",
        "third_category": "川湘菜",
        "trade_area": "万源城/东兰路",
        "wm_poi_score": 4.4
      }],
      "rank_strategy_tag": "RK4000,RK6042,RK8003",
      "rank_strategy_version": "",
      "world_cup_activity": {
        "coupon_activity_img": "",
        "coupon_activity_link": ""
      }
    },
    "code": 0,
    "msg": "成功"
  },
  bannerData: {
    "data": {
      "rcmd_board_v9": {
        "mid_ad_banner": {
          "ad_type": 7,
          "platinum_banner": {
            "ad_id": 0,
            "banner_click_url": "",
            "banner_pic_url": "http://p1.meituan.net/xianfu/bizad_ka_bjcpm_204778181537499428432581.jpg",
            "banner_tag_url": "https://s0.meituan.com/bs/waimai_ad_fe_mobile/latest/bj-var-templatesign.png",
            "brand_pic_template": 2,
            "charge_info": "planBudget=0&shopSecondType=0&kaPlanId=4026&banner_area_type=0&cityLevel=0&banner_type=0&pos=1&planType=0&orderPoiProductId=0&userId=228577344&shopThirdType=0&hostName=gh-waimai-d-ad05.gh.sankuai.com&minOrderSum=0&kaAcctId=20477818&minRoi=0.0&timeslot=0&mtdpid=2d14e701-3ddc-43ba-9d54-f05aea9fe26c&account_id=1049874&shop_id=1049874&orderType=0&ins=slot%40target_id%40ad%40plan_id%40account_id%40mtdpid&isKa=true&couponId=0&target_id=2354705&banner_id=0&appVersion=3.1.0&planAim=0&banner_pic_url=http://p1.meituan.net/xianfu/bizad_ka_bjcpm_204778181537499428432581.jpg&dt=0&aor_type=0&act_lat=0&isWeChatPackets=0&lng=121381110&secondLevelCityId=0&plan_id=2369701&user_ip=114.94.126.62&city_id=310112&adidx=0&act_lng=0&gsp_price=4&slot=44&bid=4000&lat=31150280&aor_id=0&isNR=0&rmp=RHl5ON5-yirAzpphcZp8NkfmBvIZeaCoJnAPJhssoMM0-g&orderViewId=0&brandType=1&expids={\"PLATINUM_CHARGE_UPGRADE_FLOW\":\"2803\",\"FOOD_CTR\":\"10002\",\"PLATINUM_STYLE_EXP\":\"3102\",\"PLATINUM_ADS_REORDER\":\"9501\",\"PLATINUM_FOOD_GMV_FLOW\":\"3001\",\"PLATINUM_GMV_RS_FLOW\":\"2432\",\"CTR\":\"1223\"}&templateId=pt-style-0002&prodAcctId=4042079&shopType=0&request_id=2c8bcade-3e6e-447d-9599-ebb094489704&spuIdList=1114379329,1114379344,1114341333&ad=2354705&sver=2&gsp_price_of_platinum=4.066598224639892&channel=4&gmv_k=0.0",
            "main_slogan": "惠在中秋，只因有你",
            "poi_logo": "http://p0.meituan.net/waimaipoi/cc08c046f46b48e1483f833afc6ce98a24065.jpeg",
            "poi_name": "老盛昌汤包（吴中店）",
            "products": [{
              "charge_info": "",
              "click_url": "meituanwaimai://waimai.meituan.com/menu?restaurant_id=1049874&spu_id=1114379329",
              "name": "苏州汤包（6只）",
              "origin_price": "",
              "picture": "http://p1.meituan.net/wmproductwm/43a34c2e77418624278aa59dbed72ca81405309.jpg",
              "price": "¥7",
              "spu_id": 1114379329,
              "tag_color": "#FF9027",
              "tag_info": "热卖推荐"
            }, {
              "charge_info": "",
              "click_url": "meituanwaimai://waimai.meituan.com/menu?restaurant_id=1049874&spu_id=1114379344",
              "name": "苏州汤包+咖喱牛肉粉丝汤",
              "origin_price": "",
              "picture": "http://p1.meituan.net/wmproductwm/1aa226fb6d74faaf8be6ae56833bcd041733701.jpg",
              "price": "¥15",
              "spu_id": 1114379344,
              "tag_color": "#FF9027",
              "tag_info": "热卖推荐"
            }, {
              "charge_info": "",
              "click_url": "meituanwaimai://waimai.meituan.com/menu?restaurant_id=1049874&spu_id=1114341333",
              "name": "炸猪排",
              "origin_price": "",
              "picture": "http://p0.meituan.net/wmproductwm/984db01cdd01486df53e7975b1efabf22919504.jpg",
              "price": "¥12",
              "spu_id": 1114341333,
              "tag_color": "#FF9027",
              "tag_info": "热卖推荐"
            }],
            "promotion": [],
            "sub_slogan": "传统的老味道",
            "template_type": 2,
            "wm_poi_id": 1049874
          }
        }
      }
    },
    "code": 0,
    "msg": "成功"
  },
  topBannerData: {
    "data": {
      "top_banner_list": [{
        "banner_pic_url": "http://p1.meituan.net/wmbanner/f318524efd587a16c7cfc06e49a5ada7113020.png@!style1",
        "h5_url": "https://wxapp/sub_pages/mpvue/mp-pages/page/dice/home/main?source=1&activity_id=33365&ys=2&ys_id=30969&entry_id=b_Fjxks&entry_item_id=30969",
        "banner_act_id": 30969
      }, {
        "banner_pic_url": "http://p0.meituan.net/wmbanner/242d8d1581183826e32047b725c0401c54984.png@!style1",
        "h5_url": "https://wxapp/pages/activity-invite/activity-invite?source_id=17&activity_id=30132&ys=2&ys_id=28168&entry_id=b_Fjxks&entry_item_id=28168",
        "banner_act_id": 28168
      }]
    },
    "code": 0,
    "msg": "成功"
  }
}

export {homeData}